version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=src/app.py
      # Add your S3 credentials if needed
      # - AWS_ACCESS_KEY_ID=your_access_key
      # - AWS_SECRET_ACCESS_KEY=your_secret_key
      # - S3_BUCKET=your_bucket_name
    restart: unless-stopped