model:
  name: "custom_cnn"
  input_shape: [52, 52, 1]  # Changed from [52, 52, 3]
  num_classes: 8
  dropout_rate: 0.5

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.0001
  patience: 10

data:
  test_size: 0.2
  val_size: 0.15
  random_state: 42

preprocessing:
  normalize: true

experiment:
  name: "wafer_multi_label_detection"
  tags: ["efficientnet", "multi-label"]