model:
  name: custom_cnn
  input_shape:              # Changed from [52, 52, 3]
  - 52
  - 52
  - 1
  num_classes: 8
  dropout_rate: 0.3

training:
  batch_size: 64
  epochs: 50
  learning_rate: 0.0005
  patience: 10

data:
  test_size: 0.2
  val_size: 0.15
  random_state: 42

preprocessing:
  normalize: true

experiment:
  name: wafer_multi_label_detection
  tags:
  - efficientnet
  - multi-label
